In [28]:
#!/usr/bin/env python

import cv2
import numpy as np
import os
import glob
import re
import matplotlib.pyplot as plt
import sys

sys.path.insert(0,"..")
from datImage import *
from reconstruct import *

In [29]:
# Data-set image 1 manuele point matching ([0]=letter,[1]=X-coördinaat,[2]=Y-coördinaat
data_im1 = [["J", 1734.139431, 1502.486776],
        ["M", 2091.099779, 1488.262948],
        ["I", 1661.609999, 1565.806302],
        ["N", 2046.280844, 1567.787285],
        ["P", 1805.780898, 1629.703882],
        ["H", 1657.593512, 1642.875912],
        ["Q", 1722.547093, 1658.470077],
        ["A", 2026.071171, 1673.739422],
        ["G", 1659.399943, 1716.686178],
        ["B", 2071.656303, 1762.6834],
        ["F", 1731.5232, 1799.539265],
        ["C", 2065.826781, 1841.960686],
        ["E", 1833.950791, 1891.157207],
        ["D", 1958.28922, 1897.272204]]

# test x-coördinaat im1 van J1 printen
#print(data_im1[0][1])

In [30]:
# Data-set image 2 manuele point matching ([0]=letter,[1]=X-coördinaat,[2]=Y-coördinaat
data_im2 = [["L", 1915.170419, 1462.058499],
            ["K", 1812.513428, 1480.470671],
            ["J", 1732.728582, 1529.656558],
            ["M", 2084.633373, 1529.042806],
            ["I", 1657.895905, 1587.657622],
            ["N", 2049.853088, 1613.730106],
            ["P", 1806.969629, 1673.946405],
            ["O", 1915.525147, 1678.987846],
            ["H", 1650.499504, 1675.020813],
            ["Q", 1727.412551, 1686.037037],
            ["A", 2021.47354, 1714.294708],
            ["G", 1652.173022, 1745.635367],
            ["B", 2067.638343, 1807.290379],
            ["F", 1725.98399, 1830.429187],
            ["C", 2052.176395, 1878.280232],
            ["E", 1828.44163, 1893.510187],
            ["D", 1950.202339, 1917.761312]]

# test x-coördinaat im2 van L2 printen
#print(data_im2[0][1])

In [33]:
# Functie om overeenkomende coördinaten te vinden
def vind_overeenkomende_coordinaten(data1, data2):
    overeenkomende_coordinaten = []
    
    # Loop door de eerste dataset (data1)
    for item1 in data1:
        letter1 = item1[0]
        coord1 = (item1[1], item1[2])
        
        # Loop door de tweede dataset (data2)
        for item2 in data2:
            letter2 = item2[0]
            coord2 = (item2[1], item2[2])
            
            # Controleer of de letters overeenkomen
            if letter1 == letter2:
                # Voeg overeenkomende letter en coördinaten toe aan de lijst
                overeenkomende_coordinaten.append([letter1, coord1[0], coord1[1], coord2[0], coord2[1]])
                break  # Stop met zoeken zodra een overeenkomst is gevonden

    return overeenkomende_coordinaten

# Zoek naar overeenkomende coördinaten
resultaten = vind_overeenkomende_coordinaten(data_im1, data_im2)

data_im1_im2 = []
for letter, x1, y1, x2, y2 in resultaten:
    data_im1_im2.append([letter, x1, y1, x2, y2])

# Druk de nieuwe array af
print("Array 'data_im1_im2' met overeenkomende coördinaten:")
print("Letter", "X_im1", "Y_im1", "X_im2", "Y_im2")
for row in data_im1_im2:
    print(row)


Array 'data_im1_im2' met overeenkomende coördinaten:
Letter X_im1 Y_im1 X_im2 Y_im2
['J', 1734.139431, 1502.486776, 1732.728582, 1529.656558]
['M', 2091.099779, 1488.262948, 2084.633373, 1529.042806]
['I', 1661.609999, 1565.806302, 1657.895905, 1587.657622]
['N', 2046.280844, 1567.787285, 2049.853088, 1613.730106]
['P', 1805.780898, 1629.703882, 1806.969629, 1673.946405]
['H', 1657.593512, 1642.875912, 1650.499504, 1675.020813]
['Q', 1722.547093, 1658.470077, 1727.412551, 1686.037037]
['A', 2026.071171, 1673.739422, 2021.47354, 1714.294708]
['G', 1659.399943, 1716.686178, 1652.173022, 1745.635367]
['B', 2071.656303, 1762.6834, 2067.638343, 1807.290379]
['F', 1731.5232, 1799.539265, 1725.98399, 1830.429187]
['C', 2065.826781, 1841.960686, 2052.176395, 1878.280232]
['E', 1833.950791, 1891.157207, 1828.44163, 1893.510187]
['D', 1958.28922, 1897.272204, 1950.202339, 1917.761312]


In [55]:
print(data_im1_im2)

[['J', 1734.139431, 1502.486776, 1732.728582, 1529.656558], ['M', 2091.099779, 1488.262948, 2084.633373, 1529.042806], ['I', 1661.609999, 1565.806302, 1657.895905, 1587.657622], ['N', 2046.280844, 1567.787285, 2049.853088, 1613.730106], ['P', 1805.780898, 1629.703882, 1806.969629, 1673.946405], ['H', 1657.593512, 1642.875912, 1650.499504, 1675.020813], ['Q', 1722.547093, 1658.470077, 1727.412551, 1686.037037], ['A', 2026.071171, 1673.739422, 2021.47354, 1714.294708], ['G', 1659.399943, 1716.686178, 1652.173022, 1745.635367], ['B', 2071.656303, 1762.6834, 2067.638343, 1807.290379], ['F', 1731.5232, 1799.539265, 1725.98399, 1830.429187], ['C', 2065.826781, 1841.960686, 2052.176395, 1878.280232], ['E', 1833.950791, 1891.157207, 1828.44163, 1893.510187], ['D', 1958.28922, 1897.272204, 1950.202339, 1917.761312]]


In [56]:
def find_pinholes_projections(
    filesImages,
    fileMtx,
    fileDist,
    pixel_width,
    verbose=False
):
    # Load calibration data
    mtx = np.load(fileMtx)
    dist = np.load(fileDist)
    
    # Center of image in pixels
    center = [mtx[0, 2], mtx[1, 2]]

    # Focal distance in mm
    focal_dist = pixel_width * (mtx[0, 0] + mtx[1, 1]) / 2

    # Initialize arrays to store results
    pinholes = []
    projections = []

    # Loop through each image data
    for data in filesImages:
        letter, x_im1, y_im1, x_im2, y_im2 = data
        
        # Calculate pinhole world coordinates
        if np.mean([x_im1, x_im2]) < center[0]:
            if np.mean([y_im1, y_im2]) > center[1]:
                pinhole = [-40, -65, 0]
            else:
                pinhole = [40, -65, 0]
        else:
            if np.mean([y_im1, y_im2]) > center[1]:
                pinhole = [-40, 65, 0]
            else:
                pinhole = [40, 65, 0]
        
        pinholes.append(pinhole)

        # Calculate world coordinates of projections of corners
        projections_img = []
        for x, y in [(x_im1, y_im1), (x_im2, y_im2)]:
            projection = [
                pinhole[0] + pixel_width * (center[1] - y),
                pinhole[1] - pixel_width * (center[0] - x),
                -focal_dist
            ]
            projections_img.append(projection)
        
        projections.append(projections_img)

        if verbose:
            print(f"Processing letter {letter}")

    return np.array(pinholes), np.array(projections)


In [65]:
# Define the list of image data
filesImages = data_im1_im2

# Specify file paths and pixel width
fileMtx = 'D:/2024_Marten-Thesis/Calibration/mtx.npy'
fileDist = 'D:/2024_Marten-Thesis/Calibration/dist.npy'
pixel_width = 6.12e-3  # Assuming pixel width in mm

find_pinholes_projections(filesImages,fileMtx,fileDist,pixel_width)

print("Pinhole Coordinates:")
print(pinholes)
print("\nProjections Coordinates:")
print(projections)

Pinhole Coordinates:
[[-40  65   0]
 [-40  65   0]
 [-40  65   0]
 [-40  65   0]
 [-40  65   0]
 [-40  65   0]
 [-40  65   0]
 [-40  65   0]
 [-40  65   0]
 [-40  65   0]
 [-40  65   0]
 [-40  65   0]
 [-40  65   0]
 [-40  65   0]]

Projections Coordinates:
[[[-41.46062892  68.29536501 -52.31685259]
  [-41.62690799  68.28673062 -52.31685259]]

 [[-41.37357909  70.47996234 -52.31685259]
  [-41.62315183  70.44038794 -52.31685259]]

 [[-41.84814442  67.85148489 -52.31685259]
  [-41.9818745   67.82875463 -52.31685259]]

 [[-41.86026804  70.20567046 -52.31685259]
  [-42.1414381   70.22753259 -52.31685259]]

 [[-42.23919761  68.73381079 -52.31685259]
  [-42.50996185  68.74108582 -52.31685259]]

 [[-42.31981043  67.82690399 -52.31685259]
  [-42.51653723  67.78348866 -52.31685259]]

 [[-42.41524672  68.2244199  -52.31685259]
  [-42.58395652  68.25419651 -52.31685259]]

 [[-42.50869512  70.08198726 -52.31685259]
  [-42.75689347  70.05384976 -52.31685259]]

 [[-42.77152926  67.83795935 -52.31685